config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books do
    resources :rates
  end
  root 'books#index'
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "200x200>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  belongs_to :user
  belongs_to :category
  has_many :rates
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :books
  has_many :rates
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    if params[:category].blank?
      @books = Book.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @books = Book.where(:category_id => @category_id).order("created_at DESC")
    end
  end

  def show
    if @book.rates.blank?
      @average_rate = 0
    else
      @average_rate = @book.rates.average(:ratings).round(2)
    end
  end

  def new
    @book = current_user.books.build
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def create
    @book = current_user.books.build(book_params)
    @book.category_id = params[:category_id]

    if @book.save
      redirect_to root_path
    else
      render 'new'
    end
  end


  def edit
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def update
    @book.category_id = params[:category_id]
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render 'new'
    end
  end

  def destroy
    @book.destroy
    redirect_to root_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, :author, :category_id, :image)
  end

  def find_book
    @book = Book.find(params[:id])
  end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  before_action :find_book
  before_action :find_rate, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]
  def new
    @rate = Rate.new
  end

  def create
    @rate = Rate.new(rate_params)
    @rate.book_id = @book.id
    @rate.user_id = current_user.id

    if @rate.save
      redirect_to book_path(@book)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @rate.update(rate_params)
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    @rate.destroy
    redirect_to book_path(@book)
  end

  private

  def rate_params
    params.require(:rate).permit(:ratings, :comment)
  end

  def find_book
    @book = Book.find(params[:book_id])
  end

  def find_rate
    @rate = Rate.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book, :html => { :multipart => true} do |f| %>
  <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
  <%= f.input :title, label: "Book Title" %>
  <%= f.input :image, as: :file %>
  <%= f.input :author %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/books/edit.html.erb
<%= simple_form_for @book, :html => { :multipart => true} do |f| %>
  <%= f.select :category_id, @categories %>
  <%= f.input :title, label: "Book Title" %>
  <%= f.input :author %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/books/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @books.count == 0 %>
  <h1>There are no books currently in this category</h1>
<% else %>

  <div class="row">
  <% @books.each do |book| %>
    <div class="col-md-3">
      <a href="/books/<%= book.id %>">
        <%= image_tag book.image.url(:medium), class: "book" %>
      </a>
      </div>
  <% end %>
  </div>
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= image_tag @book.image.url(:medium), class: "book-show" %>
  </div>

  <div class="col-md-8">
    <div class="book-info">
      <h3 class= "book-title"><%= @book.title %></h3>
      <h5 class= "book-author"><span>From</span> <%= @book.author %></h5>
      <h2 class= "avg-rating">Average Rating</h2>
      <div class="average-rates-ratings" data-score=<%= @average_rate %>></div>
      <span class="number-of-reviews">Based on <%= @book.rates.count %> reviews</span>
    <p class= "book-description"><%= @book.description %></p>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <!-- reviews will come here -->
    <%= render @book.rates %>
    <div>
      <%= link_to "Add Review", new_book_rate_path(@book) %>
    </div>
  </div>
</div>

<%= link_to "back", root_path %>
<% if user_signed_in? %>

  <% if @book.user_id == current_user.id %>
    <%= link_to "Edit", edit_book_path(@book) %>
    <%= link_to "Delete", book_path(@book), method: :delete, data: {confirm: "Are you sure?"} %>
  <% end %>
<% end %>

<script>
  $('.rate-ratings').raty({
    readOnly: true,
  score: function() {
    return $(this).attr('data-score');
  },
  path: '/assets/'
});
</script>

<script>
  $('.average-rates-ratings').raty({
    readOnly: true,
    path: '/assets/',
    score: function(){
      return $(this).attr( 'data-score' )}
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Review</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'partials/nav' %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <%=link_to "Reviewer", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li class = "dropdown">
          <a href="" class="dropdown-toogle" data-toggle="dropdown" role="button" aria-expanded="false">Category <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% Category.all.each do |category| %>
            <li class="<%= 'active' if params[:category] == category.name %>">
              <%= link_to category.name, books_path(category: category.name), class: "link" %>
            </li>
            <% end %>
          </ul>
        </li>

        <% if user_signed_in? %>
          <li><%= link_to "Add Book", new_book_path %></li>
          <li><%= link_to "SignOut",  destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out"%></li>
        <%else%>
         <li><%= link_to "Sign Up", new_user_registration_path, class: "glyphicon glyphicon-user" %></li>
        <li><%= link_to "Sign In",  new_user_session_path, class: "glyphicon glyphicon-log-in"%></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/rates/_form.html.erb
<%= simple_form_for([@book, @book.rates.build]) do |f| %>
  <div id="rating-form">
    <label>Rating:</label>
  </div>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

<script>
  $('#rating-form').raty({
  	path: '/assets/',
  	scoreName: 'rate[ratings]'
  });
</script>

app/views/rates/_rate.html.erb
<div class="rate-ratings" data-score=" <%= rate.ratings %>"></div>
<p><%= rate.comment %></p>

<% if user_signed_in? %>
  <% if rate.user_id == current_user.id %>

    <%= link_to "Edit", edit_book_rate_path(rate.book, rate) %>
    <%= link_to "Delete", book_rate_path(rate.book, rate), method: :delete, data: { confirm: "Are you sure?"} %>

  <% end %>
<% end %>

app/views/rates/edit.html.erb
<h1>Edit Review</h1>

<%=simple_form_for([@book, @rate]) do |f| %>
  <div id="rating-form">
    <label>Rating:</label>
  </div>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

<script>
  $('#rating-form').raty({
  	path: '/assets/',
  	scoreName: 'rate[ratings]'
  });
</script>

app/views/rates/new.html.erb
<h1> New Review</h1>

<%= render 'form' %>